### PR TITLE
Adding dynamic rate and delay

### PR DESCRIPTION
**Pull request by ghost**
This PR adds 2 new methods :
* execute_at_dynamic_rate => Allowing to compute dynamically the rate on which we execute the job
* execute_with_dynamic_delay => Allowing to compute dynamically the delay on which we execute the job

The dynamisation can be used to implement a back-off stratefy in case the job fails, and gives more flexibilty to define when the next tick of the job will be triggered.

### CODE REVIEW

**Comment by sfackler** [comment]
If the delay is typically derived from the status of the execution, it seems like it would be somewhat annoying to communicate that from one closure to the other. It could maybe instead take a single closure that does the work and returns an `Option<Duration>` representing the new delay?

**Comment by ghost** [comment]
Indeed this would be easier to compute the next delay in the closure. Returning an Option in that cas would mean that if there is a None then the job is not requeued, am i correct ?

What would be the best way in that case, updating the existing methods, or providing a new one as I did ?

**Comment by sfackler** [comment]
Yeah, None, would mean that the job is done. I think we'd want to have this as a new method.

**Comment by ghost** [comment]
Ok got it ! I'll make the update on monday then ;)

**Comment by ghost** [comment]
@sfackler That should be better now :)

**Pull request merged**
